L4Re Operating System Framework: cxx::List_item Class Reference
cxx::List_item Class Reference
Small C++ Template Library
Basic list item.
#include <list>
Inherited by cxx::T_list_item< T >.
Data Structures
class Iter
Iterator for a list of ListItem-s.
class T_iter
Iterator for derived classes from ListItem.
Public Member Functions
List_item * get_prev_item () const noexcept
Get previous item.
List_item * get_next_item () const noexcept
Get next item.
void insert_prev_item (List_item *p) noexcept
Insert item p before this item.
void insert_next_item (List_item *p) noexcept
Insert item p after this item.
void remove_me () noexcept
Remove this item from the list.
Static Public Member Functions
template<typename C , typename N >
static C * push_back (C *head, N *p) noexcept
Append item to a list.
template<typename C , typename N >
static C * push_front (C *head, N *p) noexcept
Prepend item to a list.
template<typename C , typename N >
static C * remove (C *head, N *p) noexcept
Remove item from a list.
Detailed Description
Basic list item.
Basic item that can be member of a doubly linked, cyclic list.
Definition at line 37 of file list.
Member Function Documentation
push_back()
template<typename C , typename N > C * cxx::List_item::push_back (C * head, N * p) inline static noexcept
Append item to a list.
Convenience function for empty-head corner case.
Parameters
head Pointer to the current list head.
p Pointer to new item.
Returns
the pointer to the new head.
Definition at line 248 of file list.
References insert_prev_item().
Referenced by cxx::List< D, Alloc >::push_back().
push_front()
template<typename C , typename N > C * cxx::List_item::push_front (C * head, N * p) inline static noexcept
Prepend item to a list.
Convenience function for empty-head corner case.
Parameters
head pointer to the current list head.
p pointer to new item.
Returns
the pointer to the new head.
Definition at line 259 of file list.
Referenced by cxx::List< D, Alloc >::push_front().
remove()
template<typename C , typename N > C * cxx::List_item::remove (C * head, N * p) inline static noexcept
Remove item from a list.
Convenience function for remove-head corner case.
Parameters
head pointer to the current list head.
p pointer to the item to remove.
Returns
the pointer to the new head.
Definition at line 269 of file list.
Referenced by cxx::List< D, Alloc >::remove().
The documentation for this class was generated from the following file:
l4/cxx/list